### PR TITLE
Issue #129 SLF4J Logging Structures

### PR DESCRIPTION
**Pull request by jeremiahjstacey**
I believe this work is completed and functional.

### CODE REVIEW

**Comment by xeno6696** [comment]
@kwwall There's only one conflict here, looks like it's with a change you made.  Not sure which one is the right one to pick?

**Comment by kwwall** [comment]
I'll take a look.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by kwwall** [comment]
@xeno6696 We should keep the changes that I made in **EncryptorTest.java**. That agrees how the JUnit ought to operate based on observed actual behavior. So keep my changes and discard @jeremiahjstacey  changes for **EncryptorTest.java**.

**Comment by jeremiahjstacey** [comment]
I agree. I think I had committed this during our discussion of the EncryptorTest behavior before I made the branch for that discussion.  I should have undone this change to this branch before I made the pull request.

**Pull request merged**
