### PR TITLE
Integer overflow in for loop

### PR DESCRIPTION
**Pull request by kravietz**
Fix a theoretical CWE-190 integer overflow as out.length is a long ([RandomAccessFile](https://docs.oracle.com/javase/8/docs/api/index.html?java/io/RandomAccessFile.html)) while the for loop is indexed by an int

### CODE REVIEW

**Comment by xeno6696** [comment]
@kwwall we're WAAAAY behind on this issue.  But I don't believe in closing issues if both co-leads don't agree.  I'm willing to accept all 5 commits.  

AFTER my pull request, of course... :-)

**Comment by xeno6696** [comment]
Leave it to me to not think that through.... yeah you're right, the suggested changes simply push the overflow issue to the future.  I forgot my days at Mutual of Omaha and using `BigDecimal`

**Comment by kwwall** [comment]
@xeno6696 Don't beat yourself up for missing that. I've been doing secure code reviews daily as part of my major job function for the past 4 years so I probably am more attuned to that sort of thing than you are. Plus, since it is ultimately coming from a trusted ESAPI.properties file, even the original integer overflow is probably meaningless to begin with. It really was just an attempt to shut up Coverity from complaining.

**Comment by xeno6696** [comment]
Given that the requester has not responded and the fact that the integer in question is NOT controlled by an attacker, I'm going to close this pull request.

**Pull request closed without merging**
