### PR TITLE
Enable Travis CI build

### PR DESCRIPTION
**Pull request by bkimminich**
To make it work you have to
* setup Travis CI for your repo (no special config, defaults work fine.)
* change ```secure``` into the outcome of ```travis encrypt COVERITY_SCAN_TOKEN=<Your repos coverity token>``` (should be available prepared for you on https://scan.coverity.com/projects/esapi-esapi-java-legacy/builds/new?tab=travis_ci when you have Travis set up)
* integrate with coveralls.io directly on their website (nothing else required)

Feel free to shoot me any questions or issues along the way...

### CODE REVIEW

**Comment by kwwall** [comment]
@bkimminich Before accepting this PR, 2 questions:
1) What will be the affect of removing cobertura-maven-plugin from pom.xml? Specifically, what do we lose and what do we gain?

2) In .travis.yml it looks as though you have specified JDK 7. ESAPI 2.1.x is intended to support JDK 1.6. See <requireJavaVersion> in pom.xml.  So won't that be a problem if we are building under JDK 7 for our CI builds, but we are promising people that ESAPI will work with JDK 1.6?

**Comment by xeno6696** [comment]
The JDK setting here shouldn't matter:  it just specifies the JDK the build will use.  Maven still does the actual build, and the pom is already set up for 1.6 compliance.  See the Maven compiler plugin config in pom.xml.  source and target are both 1.6.

I can't answer for cobertura, though.

**Comment by kwwall** [comment]
Okay, one down, one to go.

On Tue, Apr 12, 2016 at 11:11 PM, Matt Seil <notifications@github.com>
wrote:

> The JDK setting here shouldn't matter: it just specifies the JDK the build
> will use. Maven still does the actual build, and the pom is already set up
> for 1.6 compliance. See the Maven compiler plugin config in pom.xml. source
> and target are both 1.6.
>
> I can't answer for cobertura, though.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ESAPI/esapi-java-legacy/pull/368#issuecomment-209207157>
>



-- 
Blog: http://off-the-wall-security.blogspot.com/    | Twitter: @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by bkimminich** [comment]
The cobertura plugin wasn't removed, I just had to move it from the _reporting_ section into the _build_ section, because otherwise _coveralls_ plugin would run before the required coverage data is available. Unfortunately _coveralls_ plugins doesn't work if put into _reporting_ itself. 

Regarding the JDK I actually didn't check the pom.xml. Should be no problem though to use 6 on Travis as well, just to be sure. I can downgrade that in the PR.

Am 13. April 2016 05:11:05 MESZ, schrieb Matt Seil <notifications@github.com>:

**Comment by kwwall** [comment]
So what's everyone's thoughts on build badges when the JUnit tests
consistently failing? Should we clean that up first? (See issue #352 for
details of JUnit failures.) @xeno6696 - Do you know if Jeremiah has looked
at it any further?  I'm not as concerned about the poor code coverage
metrics at the moment (see my most recent comments on issue 4 for
esapi-java), but to me having failing tests shots to the world "We suck!"
or "We have no clue!", etc. Just sayin'. If we do have a build badge, maybe
we should disable that particular test until it gets fixed.

Thoughts?
-kevin

On Tue, Apr 12, 2016 at 11:24 PM, Björn Kimminich <notifications@github.com>
wrote:

> The cobertura plugin wasn't removed, I just had to move it from the
> _reporting_ section into the _build_ section, because otherwise _coveralls_
> plugin would run before the required coverage data is available.
> Unfortunately _coveralls_ plugins doesn't work if put into _reporting_
> itself.
>
> Regarding the JDK I actually didn't check the pom.xml. Should be no
> problem though to use 6 on Travis as well, just to be sure. I can downgrade
> that in the PR.
>
> Am 13. April 2016 05:11:05 MESZ, schrieb Matt Seil <
> notifications@github.com>:
> >The JDK setting here shouldn't matter: it just specifies the JDK the
> >build will use. Maven still does the actual build, and the pom is
> >already set up for 1.6 compliance. See the Maven compiler plugin
> >config in pom.xml. source and target are both 1.6.
> >
> >I can't answer for cobertura, though.
> >
> >---
> >You are receiving this because you were mentioned.
> >Reply to this email directly or view it on GitHub:
> >
> https://github.com/ESAPI/esapi-java-legacy/pull/368#issuecomment-209207157
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ESAPI/esapi-java-legacy/pull/368#issuecomment-209210253>
>



-- 
Blog: http://off-the-wall-security.blogspot.com/    | Twitter: @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by bkimminich** [comment]
Just tried JDK 6 but this is not available on Travis platform any more because it's out of support for almost 4 years now. But as @xeno6696 wrote it doesn't really matter as long as Maven specifies JDK 6 compiler compliance.

**Comment by kwwall** [comment]
Agree it didn't really matter; I had forgot that Travis was still using
Maven to build and thus using the pom.xml. The <requireJavaVersion>
specifying 1.6 just translates to '-source 1.6' and/or '-target 1.6' so it
doesn't really matter what version you specify in the travis.yml. That's
mostly irrelevant so even using JDK 8 would probably be okay.

And thanks for the response regarding cobertura.

Later,
-kevin

On Tue, Apr 12, 2016 at 11:35 PM, Björn Kimminich <notifications@github.com>
wrote:

> Just tried JDK 6 but this is not available on Travis platform any more
> because it's out of support for almost 4 years now. But as @xeno6696
> <https://github.com/xeno6696> wrote it doesn't really matter as long as
> Maven specifies JDK 6 compiler compliance.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ESAPI/esapi-java-legacy/pull/368#issuecomment-209212927>
>



-- 
Blog: http://off-the-wall-security.blogspot.com/    | Twitter: @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by bkimminich** [comment]
On the test issue: Having a red badge doesn't really suggest the the project team sucks. It's more likely to get an "honesty bonus" imho. Of course only if things are fixed quickly. So ignoring a flaky test is fine for short term, but should of course be fixed soon.

Regarding coverage I think for a project the age of ESAPI 2 that 70% isn't actually bad. Again, an "honestly thing" to show that. And it might motivate to continually improve it to get into the green there as well.

**Comment by chrisisbeef** [comment]
@bkimminich / @kwwall - Is this effort for ESAPI 2.x / 3.x / both?

**Comment by xeno6696** [comment]
I checked with @jeremiahjstacey last week on #352 .  He's very worried about accidentally committing something stupid, but I have relevant commits ready to merge into ESAPI as soon as he feels fine.  (Sorry J... I don't remember where we left off on that discussion!)

**Comment by b-long** [comment]
I realize I haven't been as active as @bkimminich , but I want to second his mention of an _"honesty bonus"_ .  The other thing with a red build badge (IMHO) is that it makes spending hours on a patch so much more fun!  I realize that may seem a bit silly, but I really believe in the power of gamification.  StackOverflow and green build badges are known to produce happy developers 😃

**Comment by kwwall** [comment]
@bkimminich Merged manually because of merge conflicts.

**Comment by patcheng** [comment]
Looks at git history, looks like the PR was merged in ESAPI itself back in May 7, 2016.

https://github.com/ESAPI/esapi-java-legacy/commit/cb4007fd390e6165e0d245144a70712c093e9da1

My best guess, I had a `esapi-java-legacy` forked a long time ago, and I pulled from `ESAPI` and pushed to my fork. And github thought I did some real change, and it's matching issues with the commit messages.

**Comment by kwwall** [comment]
Duh! I should have remembered to use 'git log'. Anyway, thanks. It was the reference there that said it was to close 386 that through me. Rather than issue #386, I think it was supposed to be issue #408. Issue #386 is not related to Travis at all.

**Pull request closed without merging**
