### PR TITLE
Small optimization on string case modifications

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by xeno6696** [comment]
No response.  No merge.

**Comment by valery1707** [comment]
@xeno6696 no response for what?
I don't see any question or conversation.

**Comment by xeno6696** [comment]
Because you didn’t authenticate to github.  

If you login, you’ll see my comments.  I don’t believe your change is actually optimizing anything.

**Comment by kwwall** [comment]
UpIt may do some minimal optimization, but it likely is insignificant in
light of the the rest of the overhead and places where ESAPI would
otherwise be optimized. If you can convince me with some profiling data
that these improvements are significant in some real world scenarios, we
will reconsider. But otherwise, I will stand by the comments of one of the
computer science luminaries of our generation, Donald Knuth, who said "We
should forget about small efficiencies, sat about 97% of the time:
premature optimization is the root of all evil". And it was another famous
CS instructor that I had (Jon Bentley) who taught me the wisdom of that.
Measure first, optimize second. This is the sort of thing that the JIT
optimization should normally make unnecessary.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by kwwall** [comment]
@xeno6696 Just wondering if you accidentally clicked on the 'Hide' button and unintentionally hid your comments? Because I don't see them either (despite your showing them to me in that video) when authenticated GitHub. And I've tried with using both Firefox and Chrome. Or are we looking in the wrong place? Can you find your comment, do 'Copy link' and post the direct link in a comment? Maybe that would help us to find / see it. But something strange is going on here.

**Comment by xeno6696** [comment]
@Valery1707 I’m sorry, I must seem so rude!  Not my intention!

@kwwall can’t see my comments either so I’m trying to figure out how to fix it.

**Comment by valery1707** [comment]
@xeno6696 I can't see any comments even when authenticated.

**Comment by valery1707** [comment]
@kwwall What video are you talking about? I understand your position about premature optimization and try to add some measures.

**Comment by kwwall** [comment]
@xeno6696 The video was about a 15 second one that @xeno6696 took with his iPhone and emailed me privately to show me that he had indeed commented specifically on your PR. That video showed 2 comments on specific lines of code that you committed for the PR. It's not terribly useful though. To read the comments you have to pause the video every 2 or 3 seconds so you can read it. Anyway, I'm not sure what happened, because even Matt said that he can no longer see his comments. At this point, the easiest thing might be for him to type his comments in again rather us trying to figure out why his comments are no longer showing up. But at this point it looks like GitHub ate @xeno6696's homework.

**Comment by xeno6696** [comment]
Apparently github is just smarter than me.  I created a review, but never submitted it.  That's why I could see it but not @valery1707 or @kwwall .

**Comment by jeremiahjstacey** [comment]
@xeno6696 & @valery1707 - This merge request appears to still have outstanding concerns around the benefit of changes.
From what I see thread has been inactive for 2 weeks.

If I understand the concern, there are not specific changes being requested to this content but more a concern of whether the changes being offered have the intended performance benefit to the baseline.

I would like to move this request toward resolution.  Can we agree on an action that would address concerns and keep moving forward?

From my perspective, if we had timing behavior that could show the intended impact I believe that would address concerns raised by @xeno6696.  Please correct me if I am mistaken.

If thread stays inactive for another week I intend to close the request without merging.  Note that this does not mean that everything needs to be done, just that there is an agreeable path forward and an intention to do work.

**Comment by jeremiahjstacey** [comment]
I am recommend closing this request due to inactivity.  
@kwwall or @xeno6696 

Please post a 'confirm' comment to verify agreement.

**Comment by kwwall** [comment]
@valery1707 - Will give you until the end of the month (5/31/2019) to respond to @xeno6696 review comments or make corresponding code adjustments. If it is not addressed by then, I am going to close this PR without merging.

**Comment by xeno6696** [comment]
again @valery1707 no disrespect intended, I just want to understand why your changes are an optimization.  Some data or discussion about them would be nice.  I sincerely appreciate your help and desire to contribute to this project!

**Comment by kwwall** [comment]
There has been no activity on this PR since June 5, 2019 and it is way past the May 31, 2019 date that I originally intended to wait for some sort of conclusive benchmark tests. Therefore I am rejecting this PR.

**Pull request closed without merging**
