### PR TITLE
Catching up ESAPI.properties prod and test version.

### PR DESCRIPTION
**Pull request by xeno6696**

### CODE REVIEW

**Comment by xeno6696** [comment]
@kwwall 

I actually want eyeballs on this.  

As a critique of sorts of days past, I'm *extremely* worried about the divergence between "test" and "release" in our codebase.  This is the only codebase I've worked in in 4yrs, where the test properties weren't word-for-word the same as the prod properties.  

I understand the historical reason for this, and I understand that some of these props are application specific.

**Comment by kwwall** [comment]
@xeno6696 Okay, some cleanup needed on this before merging. Here's some things that I think need to be addressed.
In `configuration/esapi/ESAPI.properties`, the following properties are **NOT** in the test version, `src/test/resources/esapi/ESAPI.properties` at all. I'm not sure if this is a mistake in production version or the test version. It may be they are needed and just don't have any unit tests or are using some default values in the JUnit tests, etc. Anyhow, those properties are:
* `HttpUtlities.UploadTempDir`
* `Validator.HTTPURI`

The property `HttpUtilities.HTTPQueryString` also appears _**twice**_ (with 2 different values!) in `configuration/esapi/ESAPI.properties`, and only once in the test version of ESAPI.properties. It appears as though you perhaps forgot to delete the old value from `configuration/esapi/ESAPI.properties`.

Lastly, at line 482 in `configuration/esapi/ESAPI.properties`, you have a comment that references Google Issue 116, in part to give credit where credit is due. Since Google Code is now shut down, I suggest instead that you refer to the corresponding GitHub Issue #126.

Strongly suggest that you fix those before merging. Also, I didn't spend a lot of time on the comments you added, but did peruse them. The looked fine at a quick glance. Let me know if you want me to scrutinize them more in depth.

**Comment by kwwall** [comment]
One more very minor cleanup... there's this comment:
#Sets whether or not will will overwrite http status codes to 200.

right before the setting of property HttpUtilities.OverwriteStatusCodes. I doubt that you meant the repeated "will will" in that comment.

**Comment by kwwall** [comment]
Hopefully, last comment on this. This property seems to be missing from `configuration/esapi/ESAPI.properties`. Not sure this is intentional. There is still a reference to it in DefaultSecurityConfiguration.java as well as in `src/test/resources/esapi/ESAPI-DualValidatorFileChecker.properties`, `src/test/resources/esapi/ESAPI-SingleValidatorFileChecker.properties`, `src/test/resources/esapi/ESAPI-QuotedValidatorFileChecker.properties`, and `src/test/resources/esapi/ESAPI-CommaValidatorFileChecker.properties`.

**Comment by xeno6696** [comment]
Hmmm...

`Validator.HTTPURI` exists in both files on line 487. 

In the prod file it appears twice.  That'll be fixed.   

I found `HttpUtlities.UploadTempDir` in both files, test:  328 (commented out) and prod: 316.  

> Hopefully, last comment on this. This property seems to be missing from configuration/esapi/ESAPI.properties. Not sure this is intentional. There is still a reference to it in DefaultSecurityConfiguration.java as well as in src/test/resources/esapi/ESAPI-DualValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-SingleValidatorFileChecker.properties, src/test/resources/esapi/ESAPI-QuotedValidatorFileChecker.properties, and src/test/resources/esapi/ESAPI-CommaValidatorFileChecker.properties.

I'm not sure which property you're referring to here....

**Comment by xeno6696** [comment]
A few values overlap between some of those files. 

Do we actually care about migrating those?  They're not even unit-tested!

**Comment by kwwall** [comment]
[esapi-props-diffs.txt](https://github.com/ESAPI/esapi-java-legacy/files/1236748/esapi-props-diffs.txt)

See attached file for all the diffs. I was wrong about HTTPURI; there are 2 in the production and only 1 in the test version, but all 3 values are different. Hopefully you can figure things out from there. I just stripped out all the comments and blank lines from each of these, sorted the properties, and then diffed the production vs the test version, but note that I did *NOT* do this on your latest update. This was based on your original PR from this from the other day. To distracted by soccer and my own coding to take time to check against your most recent version.

**Comment by xeno6696** [comment]
Okay... MasterKey and MasterSalt are present in ESAPI.properties, prod, just commented out.  

Everything else looks fine, though I do note that HTTPURL IS in both prod and test.  

I had to change nothing based upon the diff.

**Comment by xeno6696** [comment]
(Well, that I hadn't already cleaned up yesterday)

**Pull request merged**
