### PR TITLE
Issue 316 -- updated code to account for httpOnly and Secure cookie …

### PR DESCRIPTION
**Pull request by xeno6696**
@kwwall -- I can't seem to find where the "deprecated" httpOnly exists from my original comment in #316

### CODE REVIEW

**Comment by xeno6696** [comment]
@kwwall my apologies... github doesn't work like gerritt:  looks like this single pull request will also include the changes I just made for the search directory issue.  

I still need to write a series of unit tests to ensure that if those directory paths get changed again in the future, it'll cause the build to fail.

**Comment by kwwall** [comment]
@xeno6696 No worries. Regarding the JUnit tests, it wouldn't surprise me if we have any tests at all trying to load ESAPI.properties from all the legal places so it's not surprising that we missed this the last time. But if you can think of an easy way to test this via JUnit, then go for it. I did look at the most recent code change though and it looks spot on.

-kevin

**Comment by xeno6696** [comment]
@kwwall you're falling behind on reviewing all the commits here...

**Comment by xeno6696** [comment]
@jeremiahjstacey I could use your code review expertise here.  I haven't committed professional code in awhile, want to make sure I'm not stupid.

**Comment by xeno6696** [comment]
Per our conversation yesterday @kwwall I'm going to merge these changes in.  The last commits from yesterday created an Enum for the path search locations and added unit tests for when items in the enum get added/deleted and ensures that if those values ever change and the test isn't updated it'll break the build.

**Pull request merged**
