### PR TITLE
PR to fix #517 and #588

### LINKED ISSUE #517: Encoded input is not treated as an attack
behavior of `getValidInput` method in class `DefaultValidator` has been changed between versions `2.1.0.1` and `2.2.0.0`

**Example** :
`ESAPI.validator().isValidInput("QueryString", "value=%3Cscript%3Ealert(1)%3C%2Fscript%3E", 30000, true)`
**Expected**: return false
**Actual** ( version 2.1.0.1): returns false
**Actual** ( version 2.2.0.0): returns true

### PR DESCRIPTION
**Pull request by xeno6696**
@kwwall @jeremiahjstacey for the moment just try running mvn:test against this.

### CODE REVIEW

**Comment by kwwall** [comment]
@xeno6696 - Will look at this tomorrow or Saturday. My brain is fried right now.

**Comment by kwwall** [comment]
@xeno6696 - I take it that for the ESAPI.properties at least, we also want to update the one in 'configuration/esapi/ESAPI.properties' as well? Not sure about the validation.properties one. Some of that looks like it is only for testing.

Could you check and update your PR before tomorrow if possible? AntiSamy 1.6.0 just released today so I want to get a new ESAPI release out over the weekend.

**Comment by xeno6696** [comment]
@kwwall so "mvn test" does not work for me locally on the testLoggerByString and testLoggerByClass methods.  Bear that in mind.  

We have an instance here where I need guidance.  There's a legacy unit test input that fails with the changes needed to clear the two issues in question here.  When the validator runs a check on the input `jeff\WILLIAMS` as an HTTPParameterValue we get a passing unit test when we would expect a failure.  

The JavaScript codec has a possible bug, worth discussing.  If the character sequence we're interested in has a literal `\` like in the affected input, it starts to treat it like an encoded sequence.  However, since javascript encoding is hex, IE `\x###` instead of seeing the next character as `W` and returning the expected value of `\` it resets the pusbhackstring sequence and returns null.  

Thus, after the JavaScriptCodec runs `jeff\WILLIAMS` becomes `jeffWILLIAMS` which will then be the value we use to run input validation against, in this case a regex that doesn't have `\` as a whitelist, thereby the input ought to be rejected but it is accepted.  

This is probably why the original code had that funky "validate the input, THEN canonicalize, THEN validate THAT input again.  

What I haven't yet figured out is precisely what I want to do to resolve this.  It seems to me that I should find a way to finesse the JavaScriptCodec here but I don't know its escaping rules as readily as I do Java or Python--which is why it's been languishing.

**Comment by xeno6696** [comment]
I could be overthinking this.  If it's an HTTPParameterValue then we should be doing a form of canonicalization that is different.  This is like the case that prompted me to create "getCanonicalizedURI()".

**Comment by xeno6696** [comment]
It won't be done today though @kwwall

**Comment by kwwall** [comment]
@xeno6696 - I will look at it.

**Comment by jeremiahjstacey** [comment]
@kwwall , I think @xeno6696  and I were able to isolate a possible fix to the JavaScriptCodec earlier today.

The test case we're trying to prove is:

```
 public void jsEscapeTest() {
     // javascript escape syntax
        ArrayList<String> js = new ArrayList<String>();
        js.add( "JavaScriptCodec" );
        Encoder instance = new DefaultEncoder( js );
        
        assertEquals( "jeff\\WILLIAMS", instance.canonicalize("jeff\\WILLIAMS"));
    }
```
(Please note this syntax is borrowed from the JavaScriptCodec testing done in  `EncoderTest.testCanonicalize()` )

We narrowed the change required down to the `JavaScriptCodec decodeCharacter( PushbackSequence<Character>)` implementation. 

In this case the issue appears to be related to the last return of that method where the first character '\' and the second character 'W' do not represent an expected escape sequence for the Codec implementation.

[JavaScriptCodec](https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/main/java/org/owasp/esapi/codecs/JavaScriptCodec.java)

```
213      // ignore the backslash and return the character
214      return second;
```  

If we alter the default return logic to acknowledge that the first-found character '\' is  not meant to represent an escaped sequence, and therefore return null (no encoding performed), then the method appears to act as desired.

```
213		input.reset();
214		return null;
```

This change breaks one case in `EncoderTest.testCanonicalize()`:  line 235
[EncoderTest](https://github.com/ESAPI/esapi-java-legacy/blob/develop/src/test/java/org/owasp/esapi/reference/EncoderTest.java)

`235   assertEquals( "<", instance.canonicalize("\\<"));`

Updating that to expect that the backslashes are not stripped matches the updated code and allows all tests to pass.

`235  assertEquals( "\\<", instance.canonicalize("\\<"));`

Last we spoke, I believe that @xeno6696  was going to be verifying this locally and inspecting the logic for other possible implications from this change.

**Comment by xeno6696** [comment]
Analysis work done.  Specified that the test regex in src/test is NOT to be used in production, so I made that clear @kwwall .

This one's ready to ship.

**Comment by kwwall** [comment]
Okay @xeno6696 - thanks for getting on this. And @jeremiahjstacey, thanks for the assist here. I guess it was a wise decision on my part to run out for an errand because when I returned I found you had this resolved. :-)

I will fit the one remaining problem with the ValidationTest that is causing the CI workflow with Maven to fail after I merge Matt's PR.

**Pull request merged**
