### PR TITLE
Swapped tabs for spaces.

### PR DESCRIPTION
**Pull request by xeno6696**
It's finally annoying me enough.  

Can we agree to standardize on this?  Git CAN be configured to ignore whitespace changes when investigating older changes but in general I'm quite tired of seeing mixed files all the time.  Too much Python?  Maybe.

### CODE REVIEW

**Comment by xeno6696** [comment]
Super easy CR:  Clone this PR

run "git diff -w 86aa6dd9704cd0b65ca98c2aeed38b4c04fdd106" (the last commit before this one) and that will tell you all of the changes that werent whitepace.

**Comment by kwwall** [comment]
Actually,  I thought there was a way to do that from there web site too.

-kevin

**Comment by xeno6696** [comment]
Indeed.  I'm too old.  

https://github.com/ESAPI/esapi-java-legacy/pull/685/commits/79df0dd66518115c5e243ff3f6a41be32359133c?diff=split&w=1

^^Lists all the changes ignoring whitespace.

**Review by kwwall — APPROVED** [review]
You win the "easiest code review contest ever" contest.

**Comment by xeno6696** [comment]
> You win the "easiest code review contest ever" contest.

DD7492FE-9D42-4F0D-AA5D-AF0E8BAD6779

**Pull request merged**
