### PR TITLE
First public-signed commit request from Matt Seil

### PR DESCRIPTION
**Pull request by xeno6696**
This is to make a public record in the git repository that all **MY** commits in the future must be signed by me in order to be considered authentic.

### CODE REVIEW

**Comment by kwwall** [comment]
@xeno6696 - Should I just close this since your signature is now showing up as 'unverified' since you changed the expiration period (and presumably generated a new key pair)? Or do you just want to cancel your PR. Or what? The message is 'No user is associated with the committer email'.)

**Comment by xeno6696** [comment]
I was researching this and I don’t think there’s a safe way to make this work as-is.  I will close this out on my own.

**Comment by xeno6696** [comment]
I can't reproduce this locally =-/

**Comment by kwwall** [comment]
@xeno6696 wrote:
> I can't reproduce this locally =-/

Can't reproduce _what_ locally? The fact that it is unverified? Did you remember to upload your public GPG key to github.com as per https://docs.github.com/en/github/authenticating-to-github/associating-an-email-with-your-gpg-key? (I don't think github.com uses GPG key servers, unlike Sonatype / Maven Central.)

**Comment by xeno6696** [comment]
@kwwall I couldn't get "unverified" to show up locally.  What I wasn't aware of is that github conducts its own check.  I typically set all my email defaults as "xeno6696[at]gmail.com" because I still remember usenet.  Github didn't like that my `git config user.email` wasn't the canonical version of my email address.  

All is fixed now.

**Comment by kwwall** [comment]
Ha! File that under "the lies we tell ourselves". It has always amused me that people think that writing ones email address as '[at]' or '.at.' or ' at ' instead of '@' was somehow sufficient to prevent spammers from harvesting their email address. Uh huh. Yeah. Right. :)

**Pull request closed without merging**
