### PR TITLE
Jstacey 135

### PR DESCRIPTION
**Pull request by jeremiahjstacey**
This is related to the github issue #135 

In the course of discussion for this issue, it was determined that the issue as filed is intended functionality.  However, through that course we found that the behavior and intent of the tests were not entirely clear.  These changes should assist in the clarity of the SafeRequestTest by isolating the tests for the SecurityWrapperRequest implementation from the codec behavior.

Also provided is  a test-scope refactor of the implied coverage for the PercentCodec provided by the previous SafeRequestTest implementation.  Parameterized tests have been provided for asserting the PercentCodec support for both String and Character variations.  A negative test case was added for UTF16 character encoding, which is pending full implementation on that codec.

I believe this work should resolve issue 135.

### CODE REVIEW

**Comment by kwwall** [comment]
Approve your commits as long as copyright and license statement added to all new files, although other changes are suggested. See comments I just emailed to you. (I can attach them here for completeness if you think that is a good idea.)

**Comment by xeno6696** [comment]
@kwwall Assuming you're fine with the most recent push I'm ready to merge.

**Comment by kwwall** [comment]
Isn't it {@code ...} rather than @{code ...} ??? Maybe that's what you
meant though.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by jeremiahjstacey** [comment]
After doing some  (limited) research on the use of {@code} it would not let me represent the javadoc the way that I wanted.  Other formatting suggestions were using <pre> tags and other nesting for formatting.  The change to <code> felt like the most succinct solution that rendered the way I had originally intended when looking at the documentation output (in my ide).

**Pull request merged**
