### PR TITLE
fix bug not found in classpath when run with jetty or tomcat

### PR DESCRIPTION
**Pull request by JasperXgwang**
jetty or tomcat use self classloader, ClassLoader.getSystemResource use jvm classloader

### CODE REVIEW

**Comment by kwwall** [comment]
@JasperXgwang If we are to consider this PR, then we will insist on that you create a GitHub issue and associate this PR with it. In the GitHub issue, try to clearly describe what problem your PR is addressing and just as important how this will work in other environments besides just Tomcat and Jetty. That is the only way that we will accept this PR because we (humans following ESAPI) track things mostly through GitHub issues that than just commits and git commit logs. Thanks.

**Comment by JasperXgwang** [comment]
@kwwall  ok, Thanks

**Comment by xeno6696** [comment]
In the future @JasperXgwang, make sure to include the issue number in commit messages in future PRs... that way github automatically closes issues.

**Comment by xeno6696** [comment]
Fixes issue #456

**Pull request closed without merging**
