### PR TITLE
enhance: improve the performance of ObjFactory

### PR DESCRIPTION
**Pull request by hellyguo**
**Before enhance**:
> Benchmark                        Mode  Cnt       Score       Error  Units
> ObjFactoryBenchmark.benchmark1  thrpt   30  337882.228 ±  3149.328  ops/s
> ObjFactoryBenchmark.benchmark2  thrpt   30  279072.632 ± 17234.329  ops/s

**After enhanced**:
> Benchmark                        Mode  Cnt       Score       Error  Units
> ObjFactoryBenchmark.benchmark1  thrpt   30  377886.687 ± 13520.653  ops/s
> ObjFactoryBenchmark.benchmark2  thrpt   30  358412.164 ± 14730.155  ops/s

@kwwall 
Sorry for my carelessness in the previous pull request.
And, the comments is writen in English, but my English is not well. Sorry Again.

### CODE REVIEW

**Comment by jeremiahjstacey** [comment]
@kwwall  @xeno6696 
All previously listed concerns have been addressed.  I believe this is ready to merge. 

If either of you can please comment on this review with 'confirm' I will get it merged.

**Comment by kwwall** [comment]
Just got my laptop operational last night and now I'm away for 2 days
visiting my family. Will take a look when I get back home.

-kevin
--
Blog: http://off-the-wall-security.blogspot.com/  |  Twitter:  @KevinWWall
NSA: All your crypto bit are belong to us.

**Comment by xeno6696** [comment]
confirm

**Comment by jeremiahjstacey** [comment]
@xeno6696 - Noted confirmation.  

Intend to merge next Monday to allow @kwwall  time to re-review.

**Comment by kwwall** [comment]
A new test that I'm adding (`ObjectFactoryTest.testObjFactoryCache()`) shows slightly more than a 9-fold speed improvement in calls to `ObjectFactor.make()` with the cache enabled.

**Comment by hellyguo** [comment]
hi @kwwall . 

On my laptop(OS:Fedora 28/JDK:Oracle JDK 1.8.0_181), I found the new test's result failed.
```log
testObjFactoryCache: 100000 iterations.
System property [org.owasp.esapi.opsteam] is not set
System property [org.owasp.esapi.devteam] is not set
ESAPI: Attempting to load ESAPI.properties via file I/O.
ESAPI: Attempting to load ESAPI.properties as resource file via file I/O.
ESAPI: Not found in 'org.owasp.esapi.resources' directory or file not readable: /home/helly/code/github/esapi-java-legacy/ESAPI.properties
ESAPI: Found in SystemResource Directory/resourceDirectory: /home/helly/code/github/esapi-java-legacy/target/test-classes/esapi/ESAPI.properties
ESAPI: Loaded 'ESAPI.properties' properties file
ESAPI: SecurityConfiguration for Validator.ConfigurationFile.MultiValued not found in ESAPI.properties. Using default: false
ESAPI: Attempting to load validation.properties via file I/O.
ESAPI: Attempting to load validation.properties as resource file via file I/O.
ESAPI: Not found in 'org.owasp.esapi.resources' directory or file not readable: /home/helly/code/github/esapi-java-legacy/validation.properties
ESAPI: Found in SystemResource Directory/resourceDirectory: /home/helly/code/github/esapi-java-legacy/target/test-classes/esapi/validation.properties
ESAPI: Loaded 'validation.properties' properties file
testObjFactoryCache: Time with cache ENABLED (nanosec):  1201457958
testObjFactoryCache: Time with cache DISABLED (nanosec): 334148274

junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:201)
	at org.owasp.esapi.util.ObjFactoryTest.testObjFactoryCache(ObjFactoryTest.java:224)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```
Depends on JIT and other reasons, I suggest use JMH to measure the performance.

> JMH is a Java harness for building, running, and analysing nano/micro/milli/macro benchmarks written in Java and other languages targetting the JVM.

[JMH](http://openjdk.java.net/projects/code-tools/jmh/)

**Comment by kwwall** [comment]
@hellyguo Yep; you are right. This should be using JMH to do the measurements. I forgot about the JIT effects and with caching disabled, it is conceptually much easier for the JIT to optimize much of the code away on repeated tests like this. The code was primarily put into place to set the enabling/disabling in cache, which I added as for CYA purposes in case of some bizarro edge case where caching might accidentally break previously existing code. For now, I'm going to simply comment out the assertion and add a TODO comment that this needs to be rethought to use JMH similar to how it is being done in ObjFactoryBenchmark.java. I will also create a new GitHub issue on this, but I don't really want to hold up the 2.2.0.0 release for this.

**Pull request merged**
