### PR TITLE
Master branch updates for ESAPI-2.2.0.0-RC2

### PR DESCRIPTION
**Pull request by kwwall**
Corresponds to signed tag 'esapi-2.2.0.0-RC2'.

### CODE REVIEW

**Comment by fransonsr** [comment]
When was ESAPI-2.2.0.0-RC2 released? Our applications fail to load `ESAPI.properties`. The change seems to be with https://github.com/xeno6696/esapi-java-legacy/commit/283753841aa927eb535ddfddb5c899fd7721d39d 
```
in = loaders[i].getResourceAsStream(DefaultSearchPath.ROOT.toString());
```
This change attempts to load "ROOT" and not `fileName` (aka., "ESAPI.properties"). We are picking up this RC version via the transitive dependency in `encoder-esapi`:
```
        <dependency>
            <groupId>org.owasp.esapi</groupId>
            <artifactId>esapi</artifactId>
            <version>[2.0,3)</version>
        </dependency>
```

**Comment by fransonsr** [comment]
I am going to pin our app to esapi version 2.1.0.1 in the meantime.

**Comment by xeno6696** [comment]
that sucks.  SHould be an easy fix.

**Comment by xeno6696** [comment]
That bug will be fixed in the next RC.

**Comment by xeno6696** [comment]
To answer your question @fransonsr it was literally just released today, so that’s some quick feedback :-).  That said, while it was recommended in the past to compile your own version with your own properties, I’ve only ever done that myself once.

**Comment by fransonsr** [comment]
Thanks.

**Pull request merged**
